'use strict';
/**
 * Created by Ben Hu on 2016/3/3.
 */
export const SOCKET_SCAN_DEVICE = 'SOCKET_SCAN_DEVICE';
export const SOCKET_STOP_SCAN_DEVICE = 'SOCKET_STOP_SCAN_DEVICE';
export const SOCKET_SCAN_DEVICE_SUCCESS = 'SOCKET_SCAN_DEVICE_SUCCESS';
export const SOCKET_SCAN_DEVICE_FAILURE = 'SOCKET_SCAN_DEVICE_FAILURE';


export const SOCKET_CONNECT_DEVICE = 'SOCKET_CONNECT_DEVICE';
export const SOCKET_CONNECT_DEVICE_SUCCESS = 'SOCKET_CONNECT_DEVICE_SUCCESS';
export const SOCKET_CONNECT_DEVICE_FAILURE = 'SOCKET_CONNECT_DEVICE_FAILURE';

export const SOCKET_OPEN_LIGHT = 'SOCKET_OPEN_LIGHT';
export const SOCKET_OFF_LIGHT = 'SOCKET_OFF_LIGHT';

export const SOCKET_KILL_BLE_DRIVER = 'SOCKET_KILL_BLE_DRIVER';

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';