/**
 * Created by Ben Hu on 2016/6/27.
 */
export const SOCKET_SCAN_GATEWAY = 'SOCKET_SCAN_GATEWAY';
export const SOCKET_SCAN_GATEWAY_SUCCESS = 'SOCKET_SCAN_GATEWAY_SUCCESS';
export const SOCKET_SCAN_GATEWAY_FAILED = 'SOCKET_SCAN_GATEWAY_FAILED';

export const SOCKET_SCAN_DEVICE = 'SOCKET_SCAN_DEVICE';
export const SOCKET_SCAN_DEVICE_SUCCESS = 'SOCKET_SCAN_DEVICE_SUCCESS';

export const SOCKET_CONNECT_DEVICE = 'SOCKET_CONNECT_DEVICE';
export const SOCKET_CONNECT_DEVICE_SUCCESS = 'SOCKET_CONNECT_DEVICE_SUCCESS';
export const SOCKET_CONNECT_DEVICE_FAILED = 'SOCKET_CONNECT_DEVICE_FAILED';

export const SOCKET_BRIGHTNESS = 'SOCKET_BRIGHTNESS';

export const SOCKET_CONTROLLED_DEVICES = 'SOCKET_CONTROLLED_DEVICES';
export const SOCKET_CONTROLLED_DEVICES_SUCCESS = 'SOCKET_CONTROLLED_DEVICES_SUCCESS';

export const SOCKET_DISCONNECT_DEVICE = 'SOCKET_DISCONNECT_DEVICE';
export const SOCKET_DISCONNECT_DEVICE_SUCCESS = 'SOCKET_DISCONNECT_DEVICE_SUCCESS';